services:
  backend:
    build: ./backend
    container_name: hoyo_achievement_backend
    restart: always
    expose:
      - "3000"
    environment:
      - SQLITE_PATH=/app/db/sqlite.db
    volumes:
      - ./data:/app/db
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_HOST: /api
    container_name: hoyo_achievement_frontend
    restart: always
    ports:
      - "6868:80"
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net: