version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  data-loader:
    build: ./data_loader
    depends_on:
      - db
    volumes:
      - ./db/data:/app/data
    working_dir: /app
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: ${PROJECT_NAME}_backend
    restart: always
    ports:
      - "${VITE_BACKEND_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_net

  frontend:
    build: ./frontend
    container_name: ${PROJECT_NAME}_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:5173"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net: