services:
  backend:
    build: ./backend
    container_name: ${PROJECT_NAME}_backend
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_HOST: ${VITE_BACKEND_HOST}
    container_name: ${PROJECT_NAME}_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net: